#!/usr/bin/env bash
# Install the repo's git pre-commit hook.
# Part of klipper-nerdygriffin-macros
#
# Writes a .git/hooks/pre-commit stub that delegates to the tracked runner in
# .git-hooks/pre-commit. Idempotent — safe to re-run after pulling updates.
# This is a developer tool; it is intentionally NOT wired into the user-facing
# root install.sh.
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
runner="$repo_root/.git-hooks/pre-commit"
git_dir=$(git rev-parse --absolute-git-dir)
hooks_dir="$git_dir/hooks"
target="$hooks_dir/pre-commit"

if [ ! -f "$runner" ]; then
    echo "ERROR: $runner not found — are you in the klipper-nerdygriffin-macros repo?" >&2
    exit 1
fi

chmod +x "$runner"
mkdir -pv "$hooks_dir"

cat >"$target" <<'EOF'
#!/bin/sh
# Auto-generated by dev/install-git-hooks.sh — do not edit.
# Delegates to the tracked pre-commit runner in .git-hooks/.
exec "$(git rev-parse --show-toplevel)/.git-hooks/pre-commit" "$@"
EOF
chmod +x "$target"

echo "Installed: $target"
echo "        -> .git-hooks/pre-commit"

# Resolve an nvm-managed markdownlint-cli2 the same way the hook runner does,
# so this check reflects what the hook will actually see at commit time.
if ! command -v markdownlint-cli2 >/dev/null 2>&1; then
    nvm_bin=$(ls -d "$HOME"/.nvm/versions/node/*/bin 2>/dev/null | sort -V | tail -n 1)
    [ -n "$nvm_bin" ] && PATH="$nvm_bin:$PATH"
fi

if ! command -v markdownlint-cli2 >/dev/null 2>&1; then
    echo
    echo "NOTE: markdownlint-cli2 is not on PATH. The hook will abort commits until" >&2
    echo "      the Node toolchain is installed. Bootstrap it (nvm + Node + tool) with:" >&2
    echo "      dev/install-node-tools.sh   (or dev/setup.sh to do everything)" >&2
fi
